### ISSUE TITLE
Consistent identifiers for S-100/S-10x validation checks

### ISSUE THREAD

**Issue by FrankHippmann** [iho-ohi/S-100-Validation-Checks#6]
Some of the draft checks already contain check identifiers. I favour the format:

S100_4a_001

It would be great if all checks at the S-100 and product specification level could use the same format, or at least a uniform format. I also recommend that check identifiers do not get re-assigned with different iterations, even if this means that eventually we will get gaps in the identifier sequence, e.g. S100_4a_013, S100_4a_017, S100_4a_020, etc. Having consistent and immutable check identifiers will make the maintenance of validation software a lot less complex and less error prone.

I do not like the Pascal case "Short Name", e.g. CatalogStructure. For one, we should only have one official unique identifier. I prefer a "Short Description", e.g, "Check the Catalogue structure.", and/or a "Check Message", e.g., "The Catalogue structure is invalid."

**Comment by rmalyankar** [comment]
A uniform core framework works better, formats other than ISO 8211 will require format-specific elements to describe checks.

Short descriptions may have to be duplicated, for example the catalog structure could be invalid in different ways.

**Comment by LizHahessy** [comment]
Agreed at VTC 2 to follow the format:
Check ID, Description, Classification, S-100 Part, S-100 Clause, Introduced version, Modified version

Have separated out the Part number from the Check ID in case information moves Parts in the future.  Have also added an Introduced version to know which edition of the standard was being followed at the time it was introduced.  Additionally have introduced a Modified version, so if the check is edited due to changes in standard then the associated version can be noted.

For now the Check IDs is for Issue tracking purposes only, the Check IDs will be renumbered in numerical order once the first draft is ready for submission.

**Comment by LizHahessy** [comment]
Need to decide on whether we agree on the use of A, B, C etc., for when the checks may get separated later on.  This has previously happened with S-58.

**Comment by MikusRL** [comment]
About the Check ID still.

I suggest we also introduce the numbering for checks (Check ID) under development. Suggestion would be to add in front of the check number the letter "D" - S100_4a_D001. Then if the check is accepted and when published it would then "loose" the letter "D" from the check number. 

It was not really good that the checks under development had proper numbers which when published could get changed, and it is not good either now when looking at the work the DK office does for S-101 check by giving xxx to all proposed checks. It makes not easy to refer to one specific proposed check from the proposal list. 

By adding the "D" (or any other letter or symbol) at the development stage and go with the numbering as needed as well would facilitate communication at the development and later the publishing and further development of checks.

**Comment by LizHahessy** [comment]
Have agreed to use DEV IDs whilst in draft.  Closing issue.
